"""Build the information ladder for a SmolDataEnvs task.

L1 is the normal prompt. L2-L4 add what the intended computation is, derived from the task's
verified reference solution (LADDER.md). L1+schema is a control, not a rung: it adds no
information, only cheaper reading, so a gain there is a skill failure.

A task with no verified reference solution gets L1 and the control only. No rung is fabricated.

    uv run python -m smol_ladder.ladder --split test
    uv run python -m smol_ladder.ladder --split test --leak-check
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
from pathlib import Path

import pandas as pd

from smol_ladder.grade import grade, last_line
from smol_ladder.sandbox import run_script
from smol_ladder.tasks import DATA, input_dir, load_split

RUNGS = ("L1", "L2", "L3", "L4")

PROMPT = """You are solving a data-analysis question. The input tables are in ./input (read-only).

Question: {question}

Files:
{files}

Explore the data with Python as much as you need. Then write ./solution.py: a self-contained
script that reads only from ./input, computes the answer, and prints the final answer as its
LAST line of output. The final answer is just the value: a number (no commas or units),
a short label, yes/no, or a comma-separated list. Run `python3 solution.py` to check it works.
Do not look the answer up online or in any dataset; compute it from the files."""

HINT_HEADER = "\n\nA verified reference solution to this question is below. It is one correct\n" \
               "approach, not the only one."


def read_text(path: Path) -> str:
    for candidate in sorted(path.glob("*"), key=lambda p: (p.suffix != ".csv", p.name)):
        try:
            return candidate.read_text(errors="replace")[:200_000]
        except (OSError, UnicodeDecodeError):
            continue
    return ""


def schema_dump(row: dict, limit: int = 3) -> str:
    """A deterministic, model-independent dump of the relevant tables' shape.

    The control condition. Generated by script from the tables, identical for every model.
    """
    answer = str(row["answer"])
    src = input_dir(row)
    parts = []
    leaked: list[str] = []
    for name in row["files"]:
        f = src / name
        if not f.exists() or f.suffix.lower() in {".sqlite", ".db"}:
            continue
        try:
            head = pd.read_csv(f, nrows=200)
        except Exception:
            continue
        leaked += [c for c in head.columns if normalise(answer) == normalise(str(c))]
        cols = ", ".join(f"{c}: {head[c].dtype}" for c in head.columns)
        parts.append(f"{name}: {len(head.columns)} columns, {head.shape[0]}+ rows\n  columns: {cols}")
        parts.append("  first rows:\n" + head.head(limit).to_string(index=False))
    dump = "\n\n".join(parts) if parts else "(no readable tables)"
    # A column may literally be the gold answer ("winning_label"). Dropping just that column
    # keeps the control honest; the rest of the schema still carries no task information.
    for col in leaked:
        dump = dump.replace(str(col), "<label>")
    return dump


def read_source(row: dict, split: str) -> str | None:
    """The reference solution that reproduced the gold answer, or None if there is none."""
    result = DATA / "solutions" / split / row["task_id"] / "result.json"
    if not result.exists():
        return None
    if json.loads(result.read_text()).get("reward", 0.0) < 1.0:
        return None
    solution = result.parent / "solution.py"
    return solution.read_text(errors="replace") if solution.exists() else None


def strip_output(source: str) -> str:
    """L4 shows the reference program with everything that emits the answer removed.

    Removing only the final print is not enough, and measurably so: stripping just the last
    top-level print left 25/181 (13.8%) of test payloads still printing the gold answer when
    run, because agents use prints as debug output and emit a leaderboard or a per-value sweep
    before the final line. So drop *every* print/display/logging call and every docstring, not
    just the last one. leak_free() then re-runs the result and rejects whatever still leaks.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return source

    for node in ast.walk(tree):
        body = getattr(node, "body", None)
        if not isinstance(body, list) or not body:
            continue
        kept = []
        for stmt in body:
            if _emits_output(stmt):
                continue
            if (isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant)
                    and isinstance(stmt.value.value, str)):
                continue  # bare docstring
            kept.append(stmt)
        node.body = kept or [ast.Pass()]

    try:
        return ast.unparse(ast.fix_missing_locations(tree))
    except (ValueError, RecursionError):
        return source


def _emits_output(stmt: ast.stmt) -> bool:
    """Does this statement print, display, or log anything?"""
    if not isinstance(stmt, ast.Expr):
        return False
    call = stmt.value
    if not isinstance(call, ast.Call):
        return False
    name = getattr(call.func, "id", None) or getattr(call.func, "attr", None)
    return name in {"print", "display", "pprint", "show", "write", "info", "debug", "warning",
                    "error", "log", "logger"}


def redact_literals(source: str, answer: str) -> str:
    """Blank any string literal in the reference code that contains the gold answer.

    A category map like ("Drowning", r"drown") names the answer as plainly as a print does.
    Replacing the literal keeps the program runnable and its structure intact, so the rung
    still supplies the method. leak_free() is the real guard; this is cheap defence in depth.
    """
    needle = normalise(answer)
    if not needle:
        return source
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return source
    changed = False
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if needle in normalise(node.value):
                node.value = "<label>"
                changed = True
    if not changed:
        return source
    try:
        return ast.unparse(ast.fix_missing_locations(tree))
    except (ValueError, RecursionError):
        return source


def code_facts(source: str) -> dict:
    """L2: the files, columns and filters the computation touches, read off the source.

    Static, not a summary written by a model, so the rung is a function of the reference
    solution alone and identical on every run. Columns are read the way the solutions actually
    name them, df["col"], since a bare df.columns assignment is rare and a Subscript on a
    dataframe is the common case.
    """
    literals = re.findall(r"""['"]([\w./ -]{2,60})['"]""", source)
    files = sorted({s for s in literals if any(s.endswith(e) for e in
                    (".csv", ".tsv", ".parquet", ".json", ".xlsx", ".sqlite", ".db", ".txt"))})
    try:
        tree = ast.parse(source)
    except SyntaxError:
        tree = ast.Module(body=[], type_ignores=[])

    # A dataframe-ish variable: anything a read_* call is bound to, or the usual local names.
    tables: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
            func = getattr(node.value.func, "attr", getattr(node.value.func, "id", None))
            if func in {"read_csv", "read_parquet", "read_json", "read_excel", "read_sql_query",
                        "read_sql", "connect", "DataFrame"}:
                for arg in node.value.args:
                    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                        files.append(arg.value)
            if node.targets and isinstance(node.targets[0], ast.Name):
                tables.add(node.targets[0].id)
        # merged/joined frames keep the same column vocabulary
        if isinstance(node, ast.Call) and getattr(node.func, "attr", None) in {"merge", "join"}:
            if isinstance(node.func.value, ast.Name):
                tables.add(node.func.value.id)

    columns: set[str] = set()
    filters: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
            if node.value.id in tables:
                key = node.slice
                if isinstance(key, ast.Constant) and isinstance(key.value, str):
                    columns.add(key.value)
                # A boolean mask, df[df["X"] > 5], is a bare Compare, not a call.
                elif isinstance(key, ast.Compare):
                    for name, op in _compared_columns(key):
                        columns.add(name)
                        filters.append((name, op))
        # df.loc[df["X"] == "v"]
        if isinstance(node, ast.Call) and getattr(node.func, "attr", None) in {"loc", "at"}:
            for arg in node.args:
                for sub in ast.walk(arg):
                    if isinstance(sub, ast.Compare):
                        for name, op in _compared_columns(sub):
                            columns.add(name)
                            filters.append((name, op))
    return {
        "files": sorted(set(files)),
        "columns": sorted(columns)[:20],
        "filters": [f"{k} {op}" for k, op in dict.fromkeys(filters)][:12],
    }


def _compared_columns(compare: ast.Compare) -> list[tuple[str, str]]:
    """Column names appearing on either side of a comparison, with the operator."""
    out = []
    for side in (compare.left, *compare.comparators):
        for sub in ast.walk(side):
            if isinstance(sub, ast.Subscript) and isinstance(sub.slice, ast.Constant) \
                    and isinstance(sub.slice.value, str):
                out.append((sub.slice.value, _op_name(compare.ops[0])))
    return out


def _op_name(op: ast.cmpop) -> str:
    return {ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=",
            ast.Gt: ">", ast.GtE: ">="}.get(type(op), "?")


def method_hint(source: str) -> str:
    """L3: the method, stated in the reference solution's own terms."""
    calls = re.findall(r"\.(groupby|pivot_table|value_counts|agg|apply|rolling|sort_values|"
                       r"corr|cov|merge|join|fillna|dropna|describe|unique|mean|median|std|sum|"
                       r"max|min|count|nunique|to_datetime|query|loc)\s*\(", source)
    top = [c for c, _ in __import__("collections").Counter(calls).most_common(6)]
    return ", ".join(sorted(set(top)))


def prompt_for(row: dict, split: str, rung: str) -> str:
    files = "\n".join(f"- {f}" for f in row["files"])
    base = PROMPT.format(question=row["question"], files=files)
    if rung == "L1":
        return base
    if rung == "L1+schema":
        return base + f"\n\nSchema of the input tables:\n\n{schema_dump(row)}"
    source = read_source(row, split)
    if source is None:
        return base
    if rung == "L2":
        facts = code_facts(source)
        detail = (
            f"Files read: {', '.join(facts['files']) or 'the tables above'}\n"
            f"Columns used: {', '.join(facts['columns']) or '(discover them yourself)'}\n"
            f"Filters applied: {'; '.join(facts['filters']) or '(none)'}"
        )
        return base + f"\n\nNotes on the intended computation:\n\n{detail}"
    if rung == "L3":
        facts = code_facts(source)
        return (base
                + f"\n\nNotes on the intended computation:\n\n"
                + f"Files read: {', '.join(facts['files']) or 'the tables above'}\n"
                + f"Columns used: {', '.join(facts['columns']) or '(discover them yourself)'}\n"
                + f"Filters applied: {'; '.join(facts['filters']) or '(none)'}\n"
                + f"Method: {method_hint(source)}")
    if rung == "L4":
        return (base + HINT_HEADER + "\n```python\n"
                + redact_literals(strip_output(source), str(row["answer"])) + "\n```")
    raise ValueError(rung)


def leak_free(row: dict, payload: str, split: str) -> bool:
    """The leak oracle: run the stripped reference and see whether it still yields the answer.

    A string match cannot see this. A program can name the answer in a label map, a threshold
    comparison, or a hardcoded hyperparameter and never print it. So the only trustworthy test
    is behavioural: write the payload out, run it offline against the task's tables, and keep
    the rung only if it no longer grades as correct. Fails closed.
    """
    work = DATA / "ladder" / "_leakcheck" / row["task_id"]
    work.mkdir(parents=True, exist_ok=True)
    shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True, exist_ok=True)
    (work / "input").symlink_to(input_dir(row).resolve())
    (work / "solution.py").write_text(payload)
    run = run_script(work / "solution.py", work / "input", timeout=90)
    leaked = grade(row, last_line(run.stdout)) >= 1.0
    shutil.rmtree(work, ignore_errors=True)
    return not leaked


def normalise(text: str) -> str:
    return re.sub(r"[\s,_%$]", "", str(text)).lower()


# Answers this short match by accident almost anywhere: "3" occurs in every column dump,
# "yes"/"no" in prose. Flagging them would bury the real leaks in noise.
MIN_LEAK_LEN = 4


def leaks(row: dict, prompt: str) -> list[str]:
    """Does the hint hand over the answer? Checked two ways: as text, and as a number.

    The numeric test calls the dataset's own grader, so it asks exactly the question the
    reward will ask. A hand-rolled tolerance is stricter or looser than the real one by orders
    of magnitude depending on the task's rtol, which is how leaks slip through unnoticed.

    Two guards keep the signal useful. A short answer is skipped, because it matches by
    chance; and main() only counts a hit on a rung if L1 does not already have it, so an
    answer that the question itself names is never blamed on a hint.
    """
    answer = str(row["answer"])
    if len(normalise(answer)) < MIN_LEAK_LEN:
        return []
    if normalise(answer) in normalise(prompt):
        return ["answer-substring"]
    hits = []
    # Match numbers with their decimal point, not a digit run inside one: the pattern must not
    # pull "11" out of "0.11" or "1" out of "0.999", which then grade 1.0 on a loose atol and
    # turn every dumped float into a false leak.
    for match in re.finditer(r"(?<![\w.])-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", prompt):
        candidate = match.group()
        try:
            if grade(row, candidate) >= 1.0:
                hits.append(f"answer-numeric:{candidate}")
                break
        except Exception:
            continue
    return hits


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", default="test", choices=["test", "eval", "train"])
    ap.add_argument("--limit", type=int)
    ap.add_argument("--leak-check", action="store_true", default=True)
    ap.add_argument("--no-run-oracle", action="store_true",
                    help="skip running each L4 payload; much faster, but ships unverified rungs")
    args = ap.parse_args()

    rows = load_split(args.split)[: args.limit]
    out = DATA / "ladder" / args.split
    out.mkdir(parents=True, exist_ok=True)
    stats = {r: 0 for r in RUNGS}
    n_control = 0
    n_no_reference = n_excluded = 0
    real_leaks: dict[str, list[str]] = {}
    task_inherent: list[str] = []
    for i, row in enumerate(rows, 1):
        task = out / row["task_id"]
        task.mkdir(parents=True, exist_ok=True)
        record = {"task_id": row["task_id"], "difficulty_tier": row["difficulty_tier"]}
        source = read_source(row, args.split)
        have_source = source is not None
        if not have_source:
            n_no_reference += 1
        l1 = prompt_for(row, args.split, "L1")
        excluded = None
        if have_source and args.leak_check and not args.no_run_oracle:
            # Run the actual L4 payload. If stripping every print still yields the answer, the
            # rung is an answer key for this task and is dropped rather than repaired.
            payload = redact_literals(strip_output(source), str(row["answer"]))
            if not leak_free(row, payload, args.split):
                excluded = "L4-still-evaluates-to-gold"
                n_excluded += 1
        record["l4_excluded"] = excluded
        for rung in list(RUNGS) + ["L1+schema"]:
            prompt = prompt_for(row, args.split, rung)
            if args.leak_check and rung != "L4":
                # Only what a rung ADDS counts. L2-L4 are cumulative, so an answer already in
                # the question (52/250 tasks are multiple choice, where the answer is one of
                # the options) would otherwise be blamed on every hint.
                hits = leaks(row, prompt) if rung == "L1" else [
                    h for h in leaks(row, prompt) if h not in leaks(row, l1)
                ]
                if hits:
                    record.setdefault("leaks", {})[rung] = hits
                    if rung == "L1":
                        # The unmodified question already contains it: a property of the task.
                        task_inherent.append(row["task_id"])
                    else:
                        real_leaks.setdefault(row["task_id"], []).extend(
                            f"{rung}:{h}" for h in hits)
            if rung == "L1+schema":
                n_control += 1
                continue
            if excluded and rung == "L4":
                continue
            if rung == "L1" or have_source:
                (task / f"{rung}.md").write_text(prompt)
                stats[rung] += 1
        (task / "meta.json").write_text(json.dumps(record, indent=1))
        if i % 25 == 0:
            print(f"  [{i}/{len(rows)}] L4={stats['L4']} excluded={n_excluded}", flush=True)
    for task_id, hits in sorted(real_leaks.items()):
        print(f"LEAK {task_id}: {sorted(set(hits))}")
    # The funnel is the headline, not a footnote: every rung number below is conditional on it.
    print(f"{args.split}: {len(rows)} tasks")
    print(f"  no verified reference (no L2-L4): {n_no_reference}")
    print(f"  L4 excluded by run-and-grade oracle: {n_excluded}")
    print(f"  L1={stats['L1']} L2={stats['L2']} L3={stats['L3']} L4={stats['L4']} "
          f"control={n_control}")
    print(f"  residual text leaks={len(real_leaks)} task_inherent={len(set(task_inherent))}")


if __name__ == "__main__":
    main()
